### ISSUE TITLE
pglast parse failure on COPY FROM stdin;

### ISSUE THREAD

**Issue by wryun** [lelit/pglast#43]
It appears to try to parse the data as SQL. Is this expected behaviour, or a bug?

**Comment by lelit** [comment]
Can you give me an example?

**Comment by wryun** [comment]
```
pglast.parse_sql('''
CREATE TABLE foo (x smallint);
COPY foo FROM stdin;
1
2
\.
'''))

**Comment by lelit** [comment]
Ok, I tried that and I think there must some trick on the client side that
separates the data from the statement, and then passes the former as a stream
to the server. So that's not something the parser knows how to grok.

Even implementing the "CopyStmt" printer, I do not see how the tool could
handle that, but I'm obviously open to suggestions.

**Comment by wryun** [comment]
I have no familiarity with pglast, I'm afraid (and not that much experience with postgres), but my naive thought is that you could do some kind of statement by statement parse, detect when `COPY...FROM stdin` statement occurs, and don't parse the data until you hit the `\.`. You wouldn't check the format of the data, but - for me at least - the key thing is for the parser not to entirely choke.

Could be implemented as an option, I guess, since not everyone would be happy with parses that omitted data.

**Comment by lelit** [comment]
Yes, but that is trickier than my _safe_ threshold, sorry. 

I'm leaving this open in the hope that some simpler approach comes up.

**Comment by jankatins** [comment]
Actually it's psql doing the trick here:

```bash
λ cat test.sql               
CREATE TABLE foo (x smallint);
COPY foo FROM stdin;
1
2
\.
λ cat test.sql |psql postgres  
CREATE TABLE
COPY 2
```
