### ISSUE TITLE
support `create function` statements

### ISSUE THREAD

**Issue by djrobstep** [lelit/pglast#5]
I used stored functions quite a bit and would like to be able to format them.

Currently this results in:

    NotImplementedError: Printer for node 'CreateFunctionStmt' is not implemented yet

How much work would be needed to support this? Happy to look into fixing this up if you're willing to advise me on the best approach.

**Comment by lelit** [comment]
The main  showstopper is that the support for the various _PL_ languages in the underlying `libpg_query` library [is currently very limited](https://github.com/lfittl/libpg_query/issues/39).

Then there is the fact that the _DDL_ statements covered by `pg_query` is far from complete (there are tons of them!), mainly because I did not need them badly enough: as [you can see here](https://github.com/lelit/pg_query/blob/master/pg_query/printers/ddl.py#L232) I added many `CREATE xxx` printers, but the specific one you mention would require better support from `libpg_query` as stated above.

In the long run I really wish to cover all kinds of statements (as I stated [here](https://github.com/lelit/pg_query/blob/master/README.rst#id21)): writing _printers_ is not that hard, once you grok the basic mechanism... but of course each _node_ takes its time, to understand the specific AST, figure out how a prettified version should look, adding a bunch of tests, and so on.

I would be quite happy to assist you, if you think you can help.

**Comment by lelit** [comment]
This has been implemented by Ronan's commit a4b47b5582ccdd94b6d5a04e603dc517531c7206, and released in version 1.3.
