### ISSUE TITLE
support as extension in postgres logs

### ISSUE THREAD

**Issue by cabecada** [lelit/pglast#6]
Hi Team,

We are planning to send postgres logs to ELK stack.
everything works fine, but there is a concern where we log queries which are too long or problematic.

https://gist.github.com/cabecada/dd765a30f6946fdbf0bec0eb31fba047

now the concern is queries may have sensitive data wrt GDPR etc, and that creates problems logging to a centralized logging system.
  i found this extension awesome (normalize the queries) which works the best when insert/updates are not parameterized/prepared.
  
  but to my bad luck, i thought of trying to use this in an logstash plugin, but looks like jruby (logstash jruby) does not compile c extensions.
  
  now the main part:
  can you help me know if it is possible to hook this extension in the postgres logging facility and anonymize the params in the log queries.
  
  just asking, feel free to ignore. :)

**Comment by lelit** [comment]
I'm not sure I understand the issue, basically due to my ignorance about what is the "logstash plugin".

Isn't it possible to write such plugins in Python? A quick search brought me to https://stackoverflow.com/questions/38633063/scripting-in-logstash, maybe that suggests a workaround?

WRT to the "postgres logging facility", don't know that answer either, sorry: I would try asking such question on the PG mailing list, and possibly report back :)

**Comment by cabecada** [comment]
Thanks emanuele for your reply.

I agree I asked my query in the wrong context.
But I’ll ask it in the right forums.




Regards,
Vijay
________________________________
